### ISSUE TITLE
🌶️ Task 1: Get your Flask app running locally on your machine.

### ISSUE THREAD

**Issue by MAMV3x3** [MAMV3x3/MLH-Fellowship-pe-portfolio-site#10]
In this **task**, You need to set up and run the Flask app on your local machine 💻.
 - Create and activate a virtual environment using virtualenv.
 - Use pip to install all the project dependencies.
 - Set the Flask environment variable to "development" to enable debugging features.
 - Start the Flask development server.

**Comment by a-brown-code** [comment]
Success on my end!

**Comment by gibbonhug** [comment]
Success for me
