### ISSUE TITLE
🌶️ Task 3: Create a new page to display hobbies.

### ISSUE THREAD

**Issue by MAMV3x3** [MAMV3x3/MLH-Fellowship-pe-portfolio-site#12]
In this **task**, You need to create a new page that displays hobbies on the portfolio site 📄.
 - Add a new route in your Flask app to handle the new page.
 - Design and implement a template for the hobbies page.
 - Fetch and display the hobbies data dynamically.
 - Include images or visual representation for each hobby.

**Comment by MAMV3x3** [comment]
Should we link this task with #4? 🤔

**Comment by gibbonhug** [comment]
> Should we link this task with #4? thinking

While working on  task 4 I have accidentally completed this issue as well.
